[package]
name = "nbez"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]
build = "build.rs"

[dependencies]
num-traits = "0.1"

[dev-dependencies]
glutin = "0.5.0"
gfx = "0.11.0"
gfx_window_glutin = "0.11.0"